//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18010
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Swarm.Drone.Domain.Logic.RequestFactory.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Debugging {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Debugging() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Swarm.Drone.Domain.Logic.RequestFactory.Resources.Debugging", typeof(Debugging).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: Reporting is disabled and won&apos;t be performed..
        /// </summary>
        internal static string ProfiledVirtualUserNetwork_ReportingDisabled {
            get {
                return ResourceManager.GetString("ProfiledVirtualUserNetwork_ReportingDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: Reporting loop initialized..
        /// </summary>
        internal static string ProfiledVirtualUserNetwork_ReportingLoop {
            get {
                return ResourceManager.GetString("ProfiledVirtualUserNetwork_ReportingLoop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: Reporting loop terminated..
        /// </summary>
        internal static string ProfiledVirtualUserNetwork_ReportingLoopComplete {
            get {
                return ResourceManager.GetString("ProfiledVirtualUserNetwork_ReportingLoopComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: completed loop, no pending requests..
        /// </summary>
        internal static string VirtualUser_Completed {
            get {
                return ResourceManager.GetString("VirtualUser_Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: completed request..
        /// </summary>
        internal static string VirtualUser_CompletedRequest {
            get {
                return ResourceManager.GetString("VirtualUser_CompletedRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: performing request..
        /// </summary>
        internal static string VirtualUser_PerformingRequest {
            get {
                return ResourceManager.GetString("VirtualUser_PerformingRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: Aborting at user request..
        /// </summary>
        internal static string VirtualUserNetwork_Aborting {
            get {
                return ResourceManager.GetString("VirtualUserNetwork_Aborting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: Ramping up..
        /// </summary>
        internal static string VirtualUserNetwork_RampingUp {
            get {
                return ResourceManager.GetString("VirtualUserNetwork_RampingUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: Ramping... {0}  virtualusers deployed so far..
        /// </summary>
        internal static string VirtualUserNetwork_RampInProgress {
            get {
                return ResourceManager.GetString("VirtualUserNetwork_RampInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: Shutting down..
        /// </summary>
        internal static string VirtualUserNetwork_Shutdown {
            get {
                return ResourceManager.GetString("VirtualUserNetwork_Shutdown", resourceCulture);
            }
        }
    }
}
