//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Swarm.Overmind.Content.Script.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Reporting {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Reporting() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Swarm.Overmind.Content.Script.Resources.Reporting", typeof(Reporting).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Overall {
            get {
                return ResourceManager.GetString("Overall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string OverallX {
            get {
                return ResourceManager.GetString("OverallX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outcome.
        /// </summary>
        public static string OverallY {
            get {
                return ResourceManager.GetString("OverallY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average Response Time.
        /// </summary>
        public static string ResponseTime {
            get {
                return ResourceManager.GetString("ResponseTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string ResponseTimeX {
            get {
                return ResourceManager.GetString("ResponseTimeX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Respose Time (sec).
        /// </summary>
        public static string ResponseTimeY {
            get {
                return ResourceManager.GetString("ResponseTimeY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed Requests (Fail vs. Success).
        /// </summary>
        public static string ResultsCake {
            get {
                return ResourceManager.GetString("ResultsCake", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workload.
        /// </summary>
        public static string Workload {
            get {
                return ResourceManager.GetString("Workload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string WorkloadX {
            get {
                return ResourceManager.GetString("WorkloadX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requests / sec.
        /// </summary>
        public static string WorkloadY {
            get {
                return ResourceManager.GetString("WorkloadY", resourceCulture);
            }
        }
    }
}
