//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Swarm.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Constants {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Constants() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Swarm.Common.Resources.Constants", typeof(Constants).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept-Encoding.
        /// </summary>
        public static string AcceptEncoding {
            get {
                return ResourceManager.GetString("AcceptEncoding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to charset.
        /// </summary>
        public static string CharsetEncodingHeader {
            get {
                return ResourceManager.GetString("CharsetEncodingHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Views/Error/ChildAction.cshtml.
        /// </summary>
        public static string ChildActionErrorViewName {
            get {
                return ResourceManager.GetString("ChildActionErrorViewName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content-Encoding.
        /// </summary>
        public static string ContentEncoding {
            get {
                return ResourceManager.GetString("ContentEncoding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content-Type.
        /// </summary>
        public static string ContentType {
            get {
                return ResourceManager.GetString("ContentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to text/css.
        /// </summary>
        public static string CssContentType {
            get {
                return ResourceManager.GetString("CssContentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Views/Error/Index.cshtml.
        /// </summary>
        public static string ErrorViewName {
            get {
                return ResourceManager.GetString("ErrorViewName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \n.
        /// </summary>
        public static string EscapedNewLine {
            get {
                return ResourceManager.GetString("EscapedNewLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gzip.
        /// </summary>
        public static string GzipContentEncoding {
            get {
                return ResourceManager.GetString("GzipContentEncoding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to text/html; charset=utf-8.
        /// </summary>
        public static string HtmlContentType {
            get {
                return ResourceManager.GetString("HtmlContentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 400 Bad Request.
        /// </summary>
        public static string HttpBadRequest {
            get {
                return ResourceManager.GetString("HttpBadRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HEAD.
        /// </summary>
        public static string HttpHeadRequest {
            get {
                return ResourceManager.GetString("HttpHeadRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 404 Not Found.
        /// </summary>
        public static string HttpNotFound {
            get {
                return ResourceManager.GetString("HttpNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 500 Internal Server Error.
        /// </summary>
        public static string HttpServerError {
            get {
                return ResourceManager.GetString("HttpServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 200 OK.
        /// </summary>
        public static string HttpSuccess {
            get {
                return ResourceManager.GetString("HttpSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to image.
        /// </summary>
        public static string ImageContentTypeName {
            get {
                return ResourceManager.GetString("ImageContentTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Image/Upload.
        /// </summary>
        public static string ImageUploadFolder {
            get {
                return ResourceManager.GetString("ImageUploadFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 500 Internal Server Error.
        /// </summary>
        public static string InternalServerError {
            get {
                return ResourceManager.GetString("InternalServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to text/javascript.
        /// </summary>
        public static string JavaScriptContentType {
            get {
                return ResourceManager.GetString("JavaScriptContentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swarm.Overmind.Content.Script.Resources.
        /// </summary>
        public static string JavaScriptResourceNamespaceRoot {
            get {
                return ResourceManager.GetString("JavaScriptResourceNamespaceRoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.js.
        /// </summary>
        public static string JavaScriptViewNamingConvention {
            get {
                return ResourceManager.GetString("JavaScriptViewNamingConvention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .js.cshtml.
        /// </summary>
        public static string JavaScriptViewNamingExtension {
            get {
                return ResourceManager.GetString("JavaScriptViewNamingExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/json; charset=utf-8.
        /// </summary>
        public static string JsonContentType {
            get {
                return ResourceManager.GetString("JsonContentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to input-validation.
        /// </summary>
        public static string ModelValidationMessageCssClass {
            get {
                return ResourceManager.GetString("ModelValidationMessageCssClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Views.Shared.
        /// </summary>
        public static string MvcResourceSharedNamespace {
            get {
                return ResourceManager.GetString("MvcResourceSharedNamespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///.
        /// </summary>
        public static string NewLine {
            get {
                return ResourceManager.GetString("NewLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to __OpenGraphMetadata.
        /// </summary>
        public static string OpenGraphContextItem {
            get {
                return ResourceManager.GetString("OpenGraphContextItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to text/plain; charset=utf-8.
        /// </summary>
        public static string PlainTextContentType {
            get {
                return ResourceManager.GetString("PlainTextContentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Views/Post/Preview.cshtml.
        /// </summary>
        public static string PreviewPostViewName {
            get {
                return ResourceManager.GetString("PreviewPostViewName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to __RequiredScripts_{0}.
        /// </summary>
        public static string RequiredScriptsFormat {
            get {
                return ResourceManager.GetString("RequiredScriptsFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string RequiredScriptsKey {
            get {
                return ResourceManager.GetString("RequiredScriptsKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swarm.Overmind.
        /// </summary>
        public static string ResourceNamespaceRoot {
            get {
                return ResourceManager.GetString("ResourceNamespaceRoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to action.
        /// </summary>
        public static string RouteDataAction {
            get {
                return ResourceManager.GetString("RouteDataAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NotFound.
        /// </summary>
        public static string RouteDataActionNotFound {
            get {
                return ResourceManager.GetString("RouteDataActionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to controller.
        /// </summary>
        public static string RouteDataController {
            get {
                return ResourceManager.GetString("RouteDataController", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string RouteDataControllerNotFound {
            get {
                return ResourceManager.GetString("RouteDataControllerNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/rss+xml; charset=utf-8.
        /// </summary>
        public static string RssContentType {
            get {
                return ResourceManager.GetString("RssContentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server.
        /// </summary>
        public static string ServerResponseHeader {
            get {
                return ResourceManager.GetString("ServerResponseHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swarm.Common.Resources.Shared.
        /// </summary>
        public static string SharedResourceNamespaceRoot {
            get {
                return ResourceManager.GetString("SharedResourceNamespaceRoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;{0}&gt;{1}&lt;/{0}&gt;.
        /// </summary>
        public static string TagWithContents {
            get {
                return ResourceManager.GetString("TagWithContents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \\U([0-9A-F]{4}).
        /// </summary>
        public static string UnicodeRegex {
            get {
                return ResourceManager.GetString("UnicodeRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unrecoverable.exception.cshtml.
        /// </summary>
        public static string UnrecoverableExceptionViewName {
            get {
                return ResourceManager.GetString("UnrecoverableExceptionViewName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unrecoverable.cshtml.
        /// </summary>
        public static string UnrecoverableViewName {
            get {
                return ResourceManager.GetString("UnrecoverableViewName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User-Agent.
        /// </summary>
        public static string UserAgentHeader {
            get {
                return ResourceManager.GetString("UserAgentHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mozilla/5.0 (Windows NT 6.1; WOW64; rv:10.0.2) Gecko/20100101 Firefox/10.0.2.
        /// </summary>
        public static string UserAgentHeaderMock {
            get {
                return ResourceManager.GetString("UserAgentHeaderMock", resourceCulture);
            }
        }
    }
}
