//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Swarm.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Debug {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Debug() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Swarm.Common.Resources.Debug", typeof(Debug).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application shutdown..
        /// </summary>
        public static string ApplicationEnd {
            get {
                return ResourceManager.GetString("ApplicationEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application request: {0}.
        /// </summary>
        public static string ApplicationRequest {
            get {
                return ResourceManager.GetString("ApplicationRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application started..
        /// </summary>
        public static string ApplicationStart {
            get {
                return ResourceManager.GetString("ApplicationStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTML download failed for {0}.
        /// </summary>
        public static string DownloadHtmlFailed {
            get {
                return ResourceManager.GetString("DownloadHtmlFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTTP GET request failed for {0}.
        /// </summary>
        public static string DownloadHttpGetFailed {
            get {
                return ResourceManager.GetString("DownloadHttpGetFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTTP HEAD request failed for {0}.
        /// </summary>
        public static string DownloadHttpHeadFailed {
            get {
                return ResourceManager.GetString("DownloadHttpHeadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image download failed for {0}.
        /// </summary>
        public static string DownloadImageFailed {
            get {
                return ResourceManager.GetString("DownloadImageFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading HTML from {0}.
        /// </summary>
        public static string DownloadingAsHtml {
            get {
                return ResourceManager.GetString("DownloadingAsHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading image from {0}.
        /// </summary>
        public static string DownloadingAsImage {
            get {
                return ResourceManager.GetString("DownloadingAsImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate link: {0}.
        /// </summary>
        public static string DuplicateLink {
            get {
                return ResourceManager.GetString("DuplicateLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending email to {0}. Mail subject: &quot;{1}&quot;.
        /// </summary>
        public static string EmailOutgoing {
            get {
                return ResourceManager.GetString("EmailOutgoing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTTP resource wasn&apos;t an image {0}.
        /// </summary>
        public static string HttpResourceNotAnImage {
            get {
                return ResourceManager.GetString("HttpResourceNotAnImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inserting link: {0}.
        /// </summary>
        public static string InsertingLink {
            get {
                return ResourceManager.GetString("InsertingLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job {0} with ID {1} finished executing in {2}..
        /// </summary>
        public static string JobExecuted {
            get {
                return ResourceManager.GetString("JobExecuted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executing Job {0} with ID: {1}..
        /// </summary>
        public static string JobExecuting {
            get {
                return ResourceManager.GetString("JobExecuting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scheduling AutoRun job: {0}.
        /// </summary>
        public static string SchedulingAutoRunJob {
            get {
                return ResourceManager.GetString("SchedulingAutoRunJob", resourceCulture);
            }
        }
    }
}
